### ISSUE TITLE
output is not deterministic (?)

### ISSUE THREAD

**Issue by kjappelbaum** [datamol-io/safe#15]
Thanks for packaging up SAFE in such a nice package!

I've been trying 

```
safe.encode(smiles, seed=42, canonical=True, randomize=False)
```

with `smiles=CC(Cc1ccc(cc1)C(C(=O)O)C)C` (using the latest PyPi release)

but receive sometimes `c12ccc3cc1.C3(C)C(=O)O.CC(C)C2`, othertimes `c13ccc2cc1.C2(C)C(=O)O.CC(C)C3`.

I realize that the representations are equivalent but wondered if the canonical output was not supposed to be determinstic? 

Cheers,
Kevin

**Comment by hadim** [comment]
I will ping @maclandrol here as I don't know myself whether the encoding process is supposed to be deterministic or not.

**Comment by maclandrol** [comment]
Hi @kjappelbaum, this is not the intended behavior, I will investigate.

**Comment by maclandrol** [comment]
I run the following:

```python
import safe
from tqdm.auto import tqdm
smiles="CC(Cc1ccc(cc1)C(C(=O)O)C)C"

all_encodings = set([])
for i in tqdm(range(100000)):
    safe_str = safe.encode(smiles, seed=42, canonical=True, randomize=False)
    all_encodings.add(safe_str)

all_encodings
``` 
And only got  `{'c13ccc2cc1.C2(C)C(=O)O.CC(C)C3'}`

**Comment by kjappelbaum** [comment]
Thanks for looking into it: We also replicated in CI because we found it strange, too 

same code, two runs: 
https://github.com/OpenBioML/chemnlp/actions/runs/6776043063/job/18416672045?pr=482
https://github.com/OpenBioML/chemnlp/actions/runs/6776042731/job/18416671058?pr=482

**Comment by kjappelbaum** [comment]
and this is me now trying to replicate again, it is very strange 

<img width="828" alt="Screenshot 2023-11-07 at 07 11 37" src="https://github.com/datamol-io/safe/assets/32935233/5e6f797b-0869-487d-b541-17789f957a06">

**Comment by maclandrol** [comment]
I got something different `{'c12ccc3cc1.C3(C)C(=O)O.CC(C)C2'}`, when I restarted the kernel indeed. It's a bit strange. Will try a few things.

**Comment by kjappelbaum** [comment]
Fixing global seeds did not help https://app.warp.dev/block/0ewJ6yVL95bPrm8wO1eqDv. 
There might be some seed in `rdkit`, e.g. for the BRICS ordering.

**Comment by maclandrol** [comment]
I found it. See #16. It was an oversight on iterating over sets. Let me know if my fix works for you too.

**Comment by maclandrol** [comment]
@hadim will review and merge a bit later today.  Thanks for reporting it.
