### ISSUE TITLE
About generation evaluation

### ISSUE THREAD

**Issue by cbigeyes** [datamol-io/safe#21]
Hello, how to eval your model from vaildity, uniqueness and diversity? 

I used your tutorial, but get 83% validity for De Novo generation.

**Comment by maclandrol** [comment]
Hi @cbigeyes, 

Thanks for spotting this.  We used an earlier  checkpoint for the results in the paper, but uploaded the model saved at training end to huggingface. I will upload that version after the holidays. 

Thanks again !
