### ISSUE TITLE
mc_labels

### ISSUE THREAD

**Issue by orgw** [datamol-io/safe#36]
Hi, awesome stuff.

what does mc_labels contain? there's no info about it thank you

**Comment by maclandrol** [comment]
Hello @orgw, `mc_labels`  was supposed to contain molecular descriptors, so during training, the model will not only predict the next SAFE token, but also it will learn to predict some molecular descriptors (18 in total) using MSE loss. That way, we can have a full molecule representation on the EOS or CLS tokens, but also enforce some regularization on the model. 

This is not required to train the model as you can likely ignore it. Neither it is for finetuning or using it. 

We have explore small model for that purpose, but did not run all experiments. If you want to explore that double head setup, I will be happy to help.
