### ISSUE TITLE
Error in Fused Ring Systems

### ISSUE THREAD

**Issue by cbartmann** [datamol-io/safe#37]
Thanks for the amazing work. I found out that in certain cases the encoding and decoding of SMILES strings is not consistent. For example, for the canonical string: 

'CC1CCC2(C)C(CCC3C2CCC2(C)C(C(=O)CO)CCC32)C1'

In the canonical form, this string only has 3 integers, despite having 4 ring systems. The generated fragment has again 4 digits. Thus, the assignment of the attachment integer fails. Once you decode the safe string, you end up with a different molecule that now has a 7 & 4 membered ring and not as in the original a 6 and 5 membered ring.

Here is a small code snippet to reproduce the issue:

```python
import safe 
import datamol as dm
test_string = 'CC1CCC2(C)C(CCC3C2CCC2(C)C(C(=O)CO)CCC32)C1'

output_string = safe.decode(safe.encode(test_string))

print(output_string == test_string)
dm.viz.to_image([dm.to_mol(test_string), dm.to_mol(output_string)])
```
Original Molecule:
![test_string](https://github.com/datamol-io/safe/assets/73170699/3799ddb0-3f9d-46ac-8e7f-ffd9e07ee1a3)

Decoded Molecule:
![output_string](https://github.com/datamol-io/safe/assets/73170699/305d8d34-d09c-4285-a1bf-d3bfd94ba580)

**Comment by maclandrol** [comment]
Hello @cbartmann, 

Good catch. This is indeed a bug, I have pushed a fix here: https://github.com/datamol-io/safe/pull/38 

Could you check if that solves the issue ? Then I will merge and release a new version. 

Thank you.

**Comment by cbartmann** [comment]
@maclandrol Yes that solves the issue. Thanks for the quick response.
