### ISSUE TITLE
Cannot train model from scratch

### ISSUE THREAD

**Issue by Anri-Lombard** [datamol-io/safe#41]
When running the following script:

```bash
config_path="../trainer/configs/small_config.json"
tokenizer_path="../tokenizer.json"
dataset_path="../../Datasets/MOSES/datasets"
output_dir="./trained/SAFE_small"

safe-train --config $config_path \
  --tokenizer $tokenizer_path \
  --dataset $dataset_path \
  --text_column "SAFE" \
  --torch_compile True \
  --optim "adamw_torch" \
  --learning_rate 5e-4 \
  --prop_loss_coeff 1e-3 \
  --gradient_accumulation_steps 1 \
  --output_dir $output_dir \
  --num_labels 9 \
  --num_train_epochs 3 \
  --per_device_train_batch_size 8 \
  --lr_scheduler_type "linear" \
  --warmup_steps 500 \
  --logging_steps 100 \
  --evaluation_strategy "steps" \
  --eval_steps 500 \
  --save_steps 500 \
  --load_best_model_at_end True \
  --metric_for_best_model "eval_loss" \
  --greater_is_better False
 ```

I get the error:
> Traceback (most recent call last):
  File "/home/lmbanr001/.local/bin/safe-train", line 8, in <module>
    sys.exit(main())
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/cli.py", line 406, in main
    train(model_args, data_args, training_args)
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/cli.py", line 335, in train
    trainer = SAFETrainer(
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/trainer_utils.py", line 19, in __init__
    self.accelerator.dispatch_batches = dispatch_batches
AttributeError: can't set attribute 'dispatch_batches'

As I understand it, dispatch_batches is set to true when using another for of ingesting the data. Is there some intuition as to why my code is trying to set dispatch_batches?

**Comment by Anri-Lombard** [comment]
Can't this line just be safely removed since it is not used anywhere?

**Comment by Anri-Lombard** [comment]
When removing the line and running `pytest` I get no errors:

```bash
anrilombard@Anris-MacBook-Pro safe % pytest
======================================================== test session starts ========================================================
platform darwin -- Python 3.11.6, pytest-8.2.0, pluggy-1.5.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
rootdir: /Users/anrilombard/Desktop/UCT/safe
configfile: pyproject.toml
testpaths: tests
plugins: typeguard-4.2.1, Faker-23.3.0, dash-2.16.1, anyio-4.2.0
collected 20 items                                                                                                                  

tests/test_hgf_load.py::test_load_default_safe_model PASSED                                                                   [  5%]
tests/test_hgf_load.py::test_load_default_safe_tokenizer PASSED                                                               [ 10%]
tests/test_hgf_load.py::test_check_molecule_sampling PASSED                                                                   [ 15%]
tests/test_import.py::test_import PASSED                                                                                      [ 20%]
tests/test_notebooks.py::test_notebook[design-with-safe.ipynb] PASSED                                                         [ 25%]
tests/test_notebooks.py::test_notebook[getting-started.ipynb] PASSED                                                          [ 30%]
tests/test_notebooks.py::test_notebook[how-it-works.ipynb] PASSED                                                             [ 35%]
tests/test_safe.py::test_safe_encoding PASSED                                                                                 [ 40%]
tests/test_safe.py::test_safe_fragment_randomization PASSED                                                                   [ 45%]
tests/test_safe.py::test_randomized_encoder PASSED                                                                            [ 50%]
tests/test_safe.py::test_custom_encoder PASSED                                                                                [ 55%]
tests/test_safe.py::test_safe_decoder PASSED                                                                                  [ 60%]
tests/test_safe.py::test_rdkit_smiles_parser_issues PASSED                                                                    [ 65%]
tests/test_safe.py::test_bracket_smiles_issues[O=C(CN1CC[NH2+]CC1)N1CCCCC1] PASSED                                            [ 70%]
tests/test_safe.py::test_bracket_smiles_issues[[NH3+]Cc1ccccc1] PASSED                                                        [ 75%]
tests/test_safe.py::test_bracket_smiles_issues[c1cc2c(cc1[C@@H]1CCC[NH2+]1)OCCO2] PASSED                                      [ 80%]
tests/test_safe.py::test_bracket_smiles_issues[[13C]1CCCCC1C[238U]C[NH3+]] PASSED                                             [ 85%]
tests/test_safe.py::test_bracket_smiles_issues[COC[CH2:1][CH2:2]O[CH:2]C[OH:3]] PASSED                                        [ 90%]
tests/test_safe.py::test_fused_ring_issue PASSED                                                                              [ 95%]
tests/test_safe.py::test_stereochemistry_issue PASSED                                                                         [100%]
```

**Comment by Anri-Lombard** [comment]
I ran it on a smaller script:

```bash
config_path="../trainer/configs/small_config.json"
tokenizer_path="../tokenizer.json"
dataset_path="../../Datasets/MOSES/datasets"
output_dir="./trained/SAFE_small"

safe-train --config $config_path \
  --tokenizer $tokenizer_path \
  --dataset $dataset_path \
  --text_column "SAFE" \
  --torch_compile True \
  --optim "adamw_torch" \
  --learning_rate 1e-5 \
  --prop_loss_coeff 1e-3 \
  --gradient_accumulation_steps 1 \
  --output_dir $output_dir \
  --max_steps 5
  
  ```
  
  
  And still got the same error. Here it is in full:
  
  > Loading python/miniconda3-py310
  Loading requirement: compilers/gcc820 mpi/openmpi-4.0.1
2024-05-16 14:25:46.787 | INFO     | safe.trainer.cli:train:159 - Process rank: 0, device: cuda:0, n_gpu: 1 distributed training: False, 16-bits training: False
2024-05-16 14:25:46.789 | INFO     | safe.trainer.cli:train:164 - Training/evaluation parameters: TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'gradient_accumulation_kwargs': None},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./trained/SAFE_small/runs/May16_14-25-46_srvcntgpu009.uct.ac.za,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=5,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
output_dir=./trained/SAFE_small,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['wandb'],
resume_from_checkpoint=None,
run_name=./trained/SAFE_small,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=steps,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=True,
torch_compile_backend=inductor,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)
[INFO|configuration_utils.py:724] 2024-05-16 14:25:48,733 >> loading configuration file ../trainer/configs/small_config.json
[INFO|configuration_utils.py:789] 2024-05-16 14:25:48,736 >> Model config GPT2Config {
  "_name_or_path": "../trainer/configs/small_config.json",
  "activation_function": "gelu_new",
  "attn_pdrop": 0.1,
  "bos_token_id": 10000,
  "embd_pdrop": 0.1,
  "eos_token_id": 1,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6",
    "7": "LABEL_7",
    "8": "LABEL_8"
  },
  "initializer_range": 0.02,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6,
    "LABEL_7": 7,
    "LABEL_8": 8
  },
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 8,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": "tanh",
  "summary_first_dropout": 0.1,
  "summary_hidden_size": 128,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.40.2",
  "use_cache": true,
  "vocab_size": 10000
}
[INFO|configuration_utils.py:928] 2024-05-16 14:25:48,738 >> Generate config GenerationConfig {
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 3
}
2024-05-16 14:25:49.808 | INFO     | safe.trainer.cli:train:287 - Training new model from scratch - Total size=42.78M params
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
[WARNING|trainer.py:577] 2024-05-16 14:26:03,755 >> max_steps is given, it will override any value given in num_train_epochs
Traceback (most recent call last):
  File "/home/lmbanr001/.local/bin/safe-train", line 8, in <module>
    sys.exit(main())
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/cli.py", line 406, in main
    train(model_args, data_args, training_args)
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/cli.py", line 335, in train
    trainer = SAFETrainer(
  File "/home/lmbanr001/.local/lib/python3.10/site-packages/safe/trainer/trainer_utils.py", line 19, in __init__
    self.accelerator.dispatch_batches = dispatch_batches
AttributeError: can't set attribute 'dispatch_batches'

**Comment by maclandrol** [comment]
Hi @Anri-Lombard ,  `dispatch_batches` was put in place to fix a bug in transformers. 

https://github.com/huggingface/transformers/issues/26548 

What are the `transformers / accelerate` version you are using ? Could you share your minimal dataset and env for me to reproduce ?

**Comment by Anri-Lombard** [comment]
Hey @maclandrol, thanks for the feedback.

Here is the Dataset and SAFE folders I'm using; you could run the .sh script (just remove the module load, source, and deactivate command since that is how our university server loads the environment:
[SAFE.zip](https://github.com/datamol-io/safe/files/15345323/SAFE.zip)

You might have to run the preprocessing script to generate .arrow files for a valid dataset beforehand.

My transformers version is:
```bash
Name: transformers
Version: 4.40.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /scratch/lmbanr001/.local/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: safe-mol
```

And my accelerate version is:
```bash
Name: accelerate
Version: 0.30.1
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: zach.mueller@huggingface.co
License: Apache
Location: /scratch/lmbanr001/.local/lib/python3.10/site-packages
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: safe-mol
```

Here is the environment requirements:
```bash
accelerate==0.30.1
aiohttp==3.9.5
aiosignal==1.3.1
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.1
cycler==0.12.1
datamol==0.12.4
datasets==2.19.1
dill==0.3.8
docker-pycreds==0.4.0
evaluate==0.4.2
filelock==3.14.0
fonttools==4.51.0
frozenlist==1.4.1
fsspec==2024.3.1
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.23.0
idna==3.7
importlib_resources==6.4.0
Jinja2==3.1.4
joblib==1.4.2
kiwisolver==1.4.5
loguru==0.7.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
networkx==3.3
numpy==1.26.4
packaging==24.0
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
protobuf==4.25.3
psutil==5.9.8
pyarrow==16.1.0
pyarrow-hotfix==0.6
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
rdkit==2023.9.6
regex==2024.5.15
requests==2.31.0
rich==13.7.1
safe-mol==0.1.7
safetensors==0.4.3
scikit-learn==1.4.2
scipy==1.13.0
selfies==2.1.1
sentry-sdk==2.2.0
setproctitle==1.3.3
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.3.0
tqdm==4.66.4
transformers==4.40.2
typer==0.12.3
typing_extensions==4.11.0
tzdata==2024.1
universal_pathlib==0.2.2
urllib3==2.2.1
wandb==0.17.0
xxhash==3.4.1
yarl==1.9.4
```

**Comment by zhu0619** [comment]
Hi @Anri-Lombard, 
The error occurs in `accelerate >= 0.28`. 
Arguments were deprecated in `v0.28`. See https://github.com/huggingface/accelerate/releases/tag/v0.28.0.

As a temporary solution, you could downgrade your version to `0.27` for an immediate fix.
Alternatively, you may choose to wait for our upcoming release which will include this fix. 
 
 CC @maclandrol

**Comment by Anri-Lombard** [comment]
Thank you for the clarification and help @zhu0619 and @maclandrol 🙂
