### ISSUE TITLE
Data and model license clarification

### ISSUE THREAD

**Issue by rkern** [datamol-io/safe#43]
The [CC-BY license](https://creativecommons.org/licenses/by/4.0/) is very explicit about permitting commercial use, contrary to the description in the `README`:

https://github.com/datamol-io/safe/blob/main/README.md?plain=1#L163

Can you clarify what the actual license is? Is it actually CC-BY, or did you intend to apply a non-commercial license?

Thanks.

**Comment by maclandrol** [comment]
Hi @rkern, I have updated the README.  Thanks for noticing this. 

> The training dataset is licensed under CC BY 4.0. See [DATA_LICENSE](https://github.com/datamol-io/safe/blob/main/DATA_LICENSE) for details. This code base is licensed under the Apache-2.0 license. See [LICENSE](https://github.com/datamol-io/safe/blob/main/LICENSE) for details.
> Note that the model weights of SAFE-GPT are exclusively licensed for research purposes (CC BY-NC 4.0).

It's only the current model weight of SAFE-GPT that is CC BY-NC.
