### ISSUE TITLE
Parameters for smaller model

### ISSUE THREAD

**Issue by Anri-Lombard** [datamol-io/safe#44]
I trained the safe-gpt model with the 20M model configurations specified in the paper, namely:
```
{
  "activation_function": "gelu_new",
  "attn_pdrop": 0.1,
  "bos_token_id": 10000,
  "embd_pdrop": 0.1,
  "eos_token_id": 1,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-5,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 8,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": "tanh",
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_hidden_size": 128,
  "summary_use_proj": true,
  "transformers_version": "4.31.0",
  "use_cache": true,
  "vocab_size": 10000,
  "num_labels": 9
}

```

After training it ended up being a 40M parameter model. We are trying to reproduce your results for our paper; did you perhaps retrain a smaller tokenizer with a reduced vocabulary, or did you use the same tokenizer as for the 87M model? If the latter I'm not sure how the parameters ended up burgeoning beyond the paper's claims.

**Comment by maclandrol** [comment]
Hi @Anri-Lombard, 

What's the tokenizer and vocab that you are using  (we used the same tokenizer as the 87M model) ? Do you patch the vocab_size properly in the config before training ?

@FNTwin can you check if  the `n_embd`  should have been 512 and not the 768 reported in the paper ? (likely a typo we forgot to proofread in that case).

**Comment by FNTwin** [comment]
@maclandrol Typo,  the 20M model config has 
```
"n_embd": 512,
```

**Comment by maclandrol** [comment]
@Anri-Lombard, I think you should get ~20M parameters with 512.  Feel free to close the issue if you think it has been addressed.

**Comment by Anri-Lombard** [comment]
Fantastic, thank you @maclandrol and @FNTwin 🙏
